// vue2-template/src/views/About.vue
<template>
  <div class="about">
    <h1>关于</h1>
    <p>这是一个基于Vue CLI的Vue2项目模板。</p>
    <p>特性包括：</p>
    <ul>
      <li>Vue2 选项式API</li>
      <li>Vue Router 路由管理</li>
      <li>Vuex 状态管理</li>
      <li>Vue CLI 构建工具</li>
      <li>ESLint 代码检查</li>
    </ul>
  </div>
</template>

<style scoped>
.about {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  text-align: left;
}

h1 {
  color: #42b983;
  margin-bottom: 20px;
}

ul {
  line-height: 1.6;
  margin-top: 20px;
  padding-left: 20px;
}
</style>

// react-template/src/pages/About.tsx
import React from 'react';

const About: React.FC = () => {
  return (
    <div className="about">
      <h1>关于</h1>
      <p>这是一个基于React构建的项目模板。</p>
      <p>特性包括：</p>
      <ul style={{ textAlign: 'left', maxWidth: '400px', margin: '0 auto' }}>
        <li>React 18</li>
        <li>React Router 路由管理</li>
        <li>React Context 状态管理</li>
        <li>TypeScript 支持</li>
        <li>自定义Hooks</li>
        <li>组件化开发</li>
      </ul>
    </div>
  );
};

export default About;
